version: '3.3'

networks:
  web:
    external: true
  stack:
    external: false

volumes:
  database:

services:
  database:
    container_name: finalexam_database
    image: mysql:8.0
    working_dir: /var/www/html
    volumes:
      - database:/var/lib/mysql:cached
    networks:
      - stack
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=finalexam
      - MYSQL_USER=finalexam
      - MYSQL_PASSWORD=finalexam
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=''

  application:
    container_name: finalexam_application
    build:
      context: .
      dockerfile: ./docker/application/application.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    depends_on:
      - database
    extra_hosts:
      - 'finalexam.localhost:127.0.0.1'
      - 'finalexam.localhost.visuellverstehen.de:127.0.0.1'
    networks:
      - web
      - stack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finalexam.rule=Host(`finalexam.localhost`,`finalexam.localhost.visuellverstehen.de`,`finalexam.vscode.visuellverstehen.de`)"
      - "traefik.http.routers.finalexam.entrypoints=web"
      - "traefik.http.services.finalexam.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    restart: always

  tooling:
    container_name: finalexam_tooling
    build:
      context: .
      dockerfile: ./docker/tooling/tooling.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    networks:
      - stack
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    restart: always
